### PR TITLE
Add Afterlife barrel extension sound

### PR DESCRIPTION
**Pull request by nomakewan**
This adds the "thwoop" barrel extension sound as heard during the Proton Pack test fire sequence to Afterlife Mode.

### CODE REVIEW

**Comment by nomakewan** [comment]
While the code seemed straightforward enough, I do not actually have the hardware to perform a completely successful test of this PR. I'm especially concerned about debouncing (or lack thereof) on the barrel switch check. Suggestions and testing on real hardware definitely appreciated!

**Comment by gpstar81** [comment]
> While the code seemed straightforward enough, I do not actually have the hardware to perform a completely successful test of this PR. I'm especially concerned about debouncing (or lack thereof) on the barrel switch check, specifically when pushing the barrel back into the retracted position. Suggestions and testing on real hardware definitely appreciated!

Do you have a cleaner version of the sound effect without the humming of the pack in the background?

**Comment by gpstar81** [comment]
> > > While the code seemed straightforward enough, I do not actually have the hardware to perform a completely successful test of this PR. I'm especially concerned about debouncing (or lack thereof) on the barrel switch check, specifically when pushing the barrel back into the retracted position. Suggestions and testing on real hardware definitely appreciated!
> > 
> > 
> > Do you have a cleaner version of the sound effect without the humming of the pack in the background?
> 
> Did you check the one I uploaded in the PR? I did what I could to remove all the humming and whining. Listening on headphones there's the faintest bit of the high-pitched whine remaining, but my guess is that played on hardware (especially through the speaker on the Neutrona Wand) it will be imperceptible.
> 
> Could always be wrong, though!

I will try to run some high and low pass filters on it to see what I can do with it tomorrow. I am crazy busy right now getting kits built and getting one last pack code update out before sending the kits out to the distributors by the end of the week.

**Comment by nomakewan** [comment]
Uhh, looks like something is wrong in the report-core and report-addons actions. This wasn't my code doing something untoward, it appears to be an access violation for some sort of HTTP GET request in the action itself:

```
/reportsizedeltas/reportsizedeltas.py:285: DeprecationWarning: pathlib.Path.__enter__() is deprecated and scheduled for removal in Python 3.13; Path objects as a context manager is a no-op
  with artifact_folder_object as artifact_folder:
WARNING:__main__:Temporarily unable to open URL (HTTP Error 403: Forbidden), retrying
WARNING:__main__:Temporarily unable to open URL (HTTP Error 403: Forbidden), retrying
WARNING:__main__:Temporarily unable to open URL (HTTP Error 403: Forbidden), retrying
WARNING:__main__:Temporarily unable to open URL (HTTP Error 403: Forbidden), retrying
TimeoutError: Maximum number of URL load retries exceeded
```
Unfortunately the Python script doesn't report _what_ URL was causing the 403. Perhaps as maintainers you have more visibility into this issue?

**Comment by nomakewan** [comment]
I have added precompiled binaries per the discussion in #168 which reflect the changes in this PR. This PR does not include the fixes present in #166 so it would be recommended to merge that PR first, then update the precompiled binaries in this PR, then merge this.

As always I will continue to update this PR as the base repository is updated.

**Comment by nomakewan** [comment]
Going to close this for now and retarget the wand updates branch.

I did do some bench testing now that I have hardware to test on, and it's obvious that some sort of debouncing is absolutely required so prevent the sound effect from playing repeatedly when manipulating the barrel.

**Pull request closed without merging**
